/* oxlint-disable next/no-img-element -- Local assets must work in the standalone static export without an image server. */
'use client';
import {assetUrl} from './asset-path';
import { useState } from 'react';
import { ArrowUpRight, ArrowDown, MoveUpRight, Activity, Radio, Check, Copy, Download, Layers, Clock3, FileCode2, ChevronRight } from 'lucide-react';
import SensorScene from './sensor-scene';
import Benchmarks from './benchmarks';
import ProtocolExplorer from './protocol-explorer';
import MotionCapture from './motion-capture';
import type {SceneMode} from './mocap-definitions';
const PAPER='https://arxiv.org/abs/2608.11958';
const DATASET='https://doi.org/10.57967/hf/9950';
const HF='https://huggingface.co/datasets/Tdongxu/A_Synchronized_Lower_Limb_AMG_sEMG_and_Mocap';
const citation=`@misc{tang2026synchronizedamgemgdataset,
      title={Synchronized AMG and EMG Dataset of Lower-limb Muscle Activities in Everyday Training}, 
      author={Dongxu Tang and Shih Ying-Lei and Zhuoyi Ren and Jianting Liao and Yitian Shao},
      year={2026},
      eprint={2608.11958},
      archivePrefix={arXiv},
      primaryClass={cs.HC},
      url={https://arxiv.org/abs/2608.11958}, 
}`;
export default function Home() {
 const [copyState,setCopyState]=useState('');
 const [sceneMode,setSceneMode]=useState<SceneMode>('sensors');
 const copy=async()=>{try{await navigator.clipboard.writeText(citation);setCopyState('Copied');}catch{setCopyState('Copy unavailable; download BibTeX instead.');}setTimeout(()=>setCopyState(''),3000);};
 return <main>
 <a className="skip-link" href="#dataset">Skip to dataset overview</a>
 <header className="nav"><a className="wordmark" href="#explore" aria-label="SAME-Limb home">SAME<span>—</span>Limb<span className="brand-dot">.</span></a><nav aria-label="Main navigation"><a href="#dataset">Dataset</a><a href="#protocol">Protocol</a><a href="#motion-capture">Motion capture</a><a href="#results">Results</a><a href="#paper">Paper</a><a className="nav-paper" href={DATASET} target="_blank" rel="noreferrer">Get the data <ArrowUpRight size={14}/></a></nav></header>
 <section className="hero" id="explore">
  <div className="hero-copy"><div className="hero-affiliations"><a href="https://humitlab.github.io/index.html" target="_blank" rel="noreferrer" aria-label="HUMIT Lab website"><img src={assetUrl('/assets/identity/humit-lab.png')} alt="HUMIT Lab" width="425" height="142"/></a><i/><a href="https://www.hitsz.edu.cn/" target="_blank" rel="noreferrer" aria-label="Harbin Institute of Technology, Shenzhen website"><img src={assetUrl('/assets/identity/hit-shenzhen.png')} alt="Harbin Institute of Technology, Shenzhen" width="365" height="67"/></a></div><p className="eyebrow">SAME-LIMB · OPEN RESEARCH DATASET</p><h1>Synchronized AMG and EMG Dataset of Lower-limb Muscle Activities in Everyday Training</h1><p className="hero-authors"><a href="https://dongxutang918-afk.github.io/academic-site/#" target="_blank" rel="noreferrer">Dongxu Tang ↗</a> · Shih Ying-Lei · Zhuoyi Ren · Jianting Liao · Yitian Shao</p><p className="hero-institution"><a href="https://humitlab.github.io/index.html" target="_blank" rel="noreferrer">HUMIT Lab</a> · Harbin Institute of Technology, Shenzhen</p><p className="hero-desc">Synchronized acceleromyography, surface electromyography, and optical motion capture from 30 participants across 16 lower-limb task conditions.</p><div className="hero-actions"><a className="button primary" href={PAPER} target="_blank" rel="noreferrer">Read the paper <ArrowUpRight size={17}/></a><a className="text-link" href={DATASET} target="_blank" rel="noreferrer">Access dataset <MoveUpRight size={16}/></a></div><div className="hero-footnote"><div><span>AMG · 1,600 Hz</span><span>EMG · 1,000 Hz</span><span>MoCap · 90 Hz</span></div><small>1,918 trials · 4 muscle sites · bilateral knee and ankle references</small></div></div>
  <div className="hero-visual"><SensorScene mode={sceneMode} onModeChange={setSceneMode}/></div>
  <a href="#dataset" className="scroll-hint"><ArrowDown size={14}/> Dataset overview</a>
 </section>
 <section className="overview section" id="dataset"><div className="section-heading"><div><p className="eyebrow">THE DATASET</p><h2>Dataset overview</h2></div><p className="section-lead">SAME-Limb brings together acceleromyography, surface electromyography, and optical motion capture from everyday lower-limb training—a reproducible foundation for studying muscle activity and estimating joint angles.</p></div>
  <div className="stats">{[['30','healthy participants','15 female · 15 male'],['1,918','released trials','of 1,920 planned recordings'],['16','task conditions','11 functional tasks · 5 walking speeds'],['4','joint-angle outputs','Bilateral knees and ankles']].map(([n,l,s])=><div key={n}><strong>{n}</strong><span>{l}</span><small>{s}</small></div>)}</div>
  <div className="modality-grid"><article className="modality-card amg-card"><div className="card-top"><Activity size={26}/><span>01 / MECHANICAL</span></div><h3>Acceleromyography<br/><span>16 triaxial sensors</span></h3><p>Sixteen AIS2IHTR triaxial accelerometers capture local mechanical signals at four sites on the left leg.</p><footer><strong>1,600 <small>Hz</small></strong><span>Nominal processing grid</span></footer></article>
  <article className="modality-card emg-card"><div className="card-top"><Radio size={26}/><span>02 / ELECTRICAL</span></div><h3>Surface EMG<br/><span>4 matched channels</span></h3><p>Four LE230 surface EMG channels measure electrical activity at the matched RF, VM, TA, and GA muscle sites.</p><footer><strong>1,000 <small>Hz</small></strong><span>Native sampling · µV</span></footer></article>
  <MotionCapture onExplore={()=>setSceneMode('mocap')}/></div>
  <div className="research-boundary"><Layers size={21}/><p><strong>Left-leg sensing. Bilateral references.</strong> AMG and EMG were recorded only from the left leg. Right-leg angle estimates are not direct measurements of right-leg muscle activity. Joint angles are geometric labels defined by markers and segment vectors.</p><a href="https://arxiv.org/html/2608.11958v1#S3" target="_blank" rel="noreferrer" aria-label="Read the methods"><ArrowUpRight size={20}/></a></div>
 </section>
 <ProtocolExplorer/>
 <section className="section results-section" id="results"><div className="section-heading"><div><p className="eyebrow">REPRODUCIBLE BY DESIGN</p><h2>Benchmark and ablation results</h2></div><p className="section-lead">Compare model performance, task-specific errors, and acquisition configurations using the published source data.</p></div><Benchmarks/></section>
 <section className="signals-section"><div className="section"><div className="section-heading"><div><p className="eyebrow">FROM SIGNAL TO MOVEMENT</p><h2>Representative joint-angle predictions</h2></div><p className="section-lead">Representative deep-squat, vertical-jump, and 1 km/h walking trials. Black traces show MoCap labels, dashed blue traces Random Forest, and pink traces TCN.</p></div><a className="paper-figure" href={assetUrl('/assets/paper-predictions.png')} target="_blank" rel="noreferrer"><img src={assetUrl('/assets/paper-predictions.png')} loading="lazy" alt="Figure 4: left-knee, left-ankle, right-knee, and right-ankle references and predictions for three representative trials"/><span>Fig. 4 · Open original <ArrowUpRight size={16}/></span></a><p className="signal-note">Representative trials complement the aggregate evaluation; they do not replace it. Source: arXiv:2608.11958v1, Fig. 4.</p></div></section>
 <section className="section access-section" id="access"><div className="section-heading"><div><p className="eyebrow">READY FOR YOUR RESEARCH</p><h2>Data access and reproducibility</h2></div><a className="button primary" href={DATASET} target="_blank" rel="noreferrer">Get the dataset <ArrowUpRight size={18}/></a></div>
  <div className="access-grid"><article><FileCode2 size={26}/><h3>Complete trial data</h3><p>1,918 NPZ files with AMG, EMG, MoCap, joint angles, validity masks, and modality-specific time vectors.</p><a href={HF+'/tree/main/data/trials'} target="_blank" rel="noreferrer">Browse trials <ChevronRight size={16}/></a></article><article><Layers size={26}/><h3>Reproducible benchmarks</h3><p>Fixed splits, window manifests, 64 fitted model artifacts, reference predictions, and source tables.</p><a href={HF+'/tree/main/code'} target="_blank" rel="noreferrer">Explore benchmark code <ChevronRight size={16}/></a></article><article><Clock3 size={26}/><h3>Documented timing</h3><p>AMG streams share a common grid. All modalities are cropped to their shared interval; labels use the nearest native MoCap frame.</p><a href={HF+'#acquisition-clocks-and-time-alignment'} target="_blank" rel="noreferrer">Read the data guide <ChevronRight size={16}/></a></article></div>
  <div className="technical-notes"><details><summary>Data format and synchronization</summary><div><p>The four AMG streams are linearly interpolated onto a nominal 1,600 Hz grid, without extrapolation. EMG retains its native 1,000 Hz sampling rate; MoCap retains native frame timestamps. Device clocks were coordinated by NTP, with no additional correction for cross-device clock offset or drift. Hardware-level synchronization accuracy was not established.</p><p>NPZ arrays include <code>amg_raw_aligned</code>, <code>amg_dc_corrected_aligned</code>, <code>amg_highpass_5hz_aligned</code>, <code>semg_raw</code>, <code>semg_preprocessed_basic</code>, <code>motion_markers_named</code>, <code>motion_skeleton_selected</code>, <code>joint_angles_deg</code> and <code>joint_angle_valid_mask</code>, provided alongside modality-specific time vectors and <code>metadata_json</code>. Raw AMG values are stored in g/digit; multiply by 19.14258 to convert to mm/s².</p><p>Auditory cue records are available for 1,726 trials and absent for 192. They were not used for alignment or benchmark computation.</p></div></details><details><summary>Scope, ethics, and licensing</summary><div><p>Participants were healthy adults aged 23.4 ± 2.1 years. Clinical generalization to patients or other populations has not been validated. The study was approved by the Medical Ethics Committee of Harbin Institute of Technology (HIT-2024046; 8 July 2024). All participants provided written informed consent.</p><p>Data, metadata, research source materials, predictions, metrics, and trained models are licensed under CC BY 4.0; <code>code/</code> software uses Apache-2.0. Third-party materials retain their original terms. The article and Supplementary Information have separate publication licenses.</p><a href={HF+'/blob/main/LICENSING.md'} target="_blank" rel="noreferrer">Read the full licensing terms ↗</a></div></details><details><summary>Interactive anatomy and hardware references</summary><div><p>The model uses a CC0 MakeHuman-derived mesh with an illustrative walking cycle and arms crossed over the chest. Transparent left-leg skin reveals schematic RF, VM, TA, and GA muscles. Fifteen reflective markers follow the lower-body segments; positions are schematic rather than measured participant coordinates.</p><p>LE230 geometry follows Biometrics dimensions: 42 × 24 × 14 mm. The AIS2IHTR IC measures 2 × 2 × 0.93 mm; its custom carrier board is illustrated at approximately 6 × 5 mm, estimated from paper Fig. 1. Devices use these dimensions in the physical-scale layout; selection temporarily enlarges one sensor for inspection.</p><p>Product reference images belong to Biometrics Ltd and STMicroelectronics. The human mesh was distributed through MakeHuman / MPFB2, NAVER anny, and three.ws.</p><a href={assetUrl('/assets/PROVENANCE.md')} target="_blank" rel="noreferrer">View model license and hardware sources ↗</a></div></details></div>
 </section>
 <section className="paper-section" id="paper"><div className="section"><p className="eyebrow">THE PAPER</p><div className="publication"><div><span className="paper-tag">arXiv:2608.11958v1 · 12 AUG 2026</span><h2>Synchronized AMG and EMG Dataset of Lower-limb Muscle Activities in Everyday Training</h2><p className="authors">Dongxu Tang · Shih Ying-Lei · Zhuoyi Ren · Jianting Liao · Yitian Shao</p><p className="affiliation">School of Computer Science and Technology<br/>Harbin Institute of Technology, Shenzhen</p><div className="hero-actions"><a className="button dark-button" href={PAPER} target="_blank" rel="noreferrer">Read the paper <ArrowUpRight size={17}/></a><a className="text-link" href="https://arxiv.org/pdf/2608.11958" target="_blank" rel="noreferrer">Download PDF <Download size={16}/></a></div></div><div className="citation-panel"><div className="citation-top"><span>Cite this work</span><button onClick={copy}>{copyState==='Copied'?<Check size={15}/>:<Copy size={15}/>} {copyState||'Copy BibTeX'}</button></div><pre><code>{citation}</code></pre><footer><span>Please cite the arXiv paper.</span><a download="SAME-Limb.bib" href={'data:text/plain;charset=utf-8,'+encodeURIComponent(citation)}>Download .bib <Download size={13}/></a></footer><span className="sr-only" aria-live="polite">{copyState}</span></div></div></div></section>
 <footer className="footer"><a className="wordmark" href="#explore">SAME<span>—</span>Limb<span className="brand-dot">.</span></a><p>Synchronized lower-limb muscle activity and kinematics.</p><div><a href={DATASET} target="_blank" rel="noreferrer">Dataset DOI <ArrowUpRight size={13}/></a><a href={PAPER} target="_blank" rel="noreferrer">Paper <ArrowUpRight size={13}/></a><a href="https://dongxutang918-afk.github.io/academic-site/#" target="_blank" rel="noreferrer">Dongxu Tang ↗</a><a href="https://humitlab.github.io/index.html" target="_blank" rel="noreferrer">HUMIT Lab ↗</a><span>Dataset v2.0.3</span></div><small>Based on arXiv v1 and dataset v2.0.3 · Anatomy and motion are illustrative.</small></footer>
 </main>;
}


