export type TaskProtocol={name:string;image:number;setup:string;execution:string;standard:string;timing:'static'|'cued'|'walking'};
export const protocols:Record<string,TaskProtocol>={
 'Quiet Stand':{name:'Quiet stand',image:0,setup:'Stand upright with both feet approximately shoulder-width apart.',execution:'Maintain the standing posture for the full recording interval.',standard:'Keep the arms crossed over the chest and maintain the prescribed foot position.',timing:'static'},
 'Quiet Sit':{name:'Quiet sit',image:1,setup:'Sit on the chair with the trunk upright and legs relaxed.',execution:'Maintain the seated posture throughout the recording interval.',standard:'Keep the trunk upright; this is a static recording without repeated cue-paced movements.',timing:'static'},
 'Deadlift':{name:'Deadlift',image:2,setup:'Stand with feet approximately shoulder-width apart and toes slightly outward. The box contains two 500-sheet reams of A4 paper.',execution:'Lower and lift the box within approximately four seconds. Keep the trunk upright during lifting and look forward.',standard:'Adjust the initial box height using one supporting ream for the nominal 155–165 cm height band, two for 165–175 cm, and three above approximately 175 cm. Study personnel select the recorded height band. Align the support-stack corners with the foot directions. Hands hold the box.',timing:'cued'},
 'Deep Squat':{name:'Deep squat',image:3,setup:'Use the same foot placement and height-adjusted box arrangement as in the Deadlift condition, with no standardized load inside the box.',execution:'Complete the squat movement according to the auditory cues.',standard:'Retain the prescribed box arrangement and task form across repetitions. The load inside the box, rather than the height-adjustment arrangement, distinguishes this setup from the Deadlift.',timing:'cued'},
 'Stair Ascent':{name:'Stair ascent',image:4,setup:'Use the same step arrangement across trials.',execution:'Lead the upward phase with the left leg and use the right leg during the downward phase.',standard:'Follow the specified leg order and auditory cues; keep the arms crossed unless hand contact is required.',timing:'cued'},
 'Left Lunge':{name:'Left lunge',image:5,setup:'Place the left foot at approximately 45° and allow the right leg to remain relaxed.',execution:'Advance the left knee forward beyond the toes using the standardized study form.',standard:'Maintain the prescribed foot angle and complete the movement according to the auditory cues.',timing:'cued'},
 'Single-leg Stance':{name:'Single-leg stance',image:6,setup:'Raise the right leg before recording and establish stable balance on the left leg.',execution:'Start the trial at 0 s only after balance is stable, then hold the posture for the full recording interval.',standard:'Keep the toes of the raised foot approximately parallel to the floor. This is a sustained balance task, without repeated cue-paced movements.',timing:'static'},
 'Forward Lunge':{name:'Forward lunge',image:7,setup:'Use a relative foot angle of approximately 30°.',execution:'Advance the front knee forward beyond the toes according to the standardized study form.',standard:'Maintain the prescribed relative foot angle and follow the auditory cues.',timing:'cued'},
 'Vertical Jump':{name:'Vertical jump',image:8,setup:'Begin with feet approximately shoulder-width apart.',execution:'Perform a vertical jump in place and return to the starting area.',standard:'Follow the auditory cues and preserve the starting area across repetitions.',timing:'cued'},
 'Stand-sit transition':{name:'Stand–sit transition',image:9,setup:'Position the chair with its front edge aligned to the posterior lower-leg/heel line.',execution:'Begin standing and perform the instructed stand-to-sit transition according to the auditory cues.',standard:'Keep the chair in the same prescribed position across trials.',timing:'cued'},
 'Heel Raise':{name:'Heel raise',image:10,setup:'Begin with both feet approximately shoulder-width apart.',execution:'Perform a bilateral heel raise within each cue interval.',standard:'Raise both heels using the prescribed foot placement and auditory timing.',timing:'cued'},
};
for(const speed of [1,2,3,4,5])protocols[`Walk at ${speed} km/h`]={name:`Walking · ${speed} km/h`,image:11,setup:`Bring the treadmill to ${speed} km/h before recording. Allow the participant to adapt until walking appears stable.`,execution:'Record approximately 15 seconds of stable walking at the target speed.',standard:'Schedule four trials at this speed. Study personnel observe the participant and pause recording when rest is required. Walking is not paced by repeated auditory cues.',timing:'walking'};
export const taskNames=Object.fromEntries(Object.entries(protocols).map(([key,value])=>[key,value.name]));
